# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jonathanpascu/CLionProjects/medcine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jonathanpascu/CLionProjects/medcine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jonathanpascu/CLionProjects/medcine/CMakeFiles /Users/jonathanpascu/CLionProjects/medcine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jonathanpascu/CLionProjects/medcine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named medcine

# Build rule for target.
medcine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 medcine
.PHONY : medcine

# fast build rule for target.
medcine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/build
.PHONY : medcine/fast

Enter_CPR_.o: Enter_CPR_.c.o
.PHONY : Enter_CPR_.o

# target to build an object file
Enter_CPR_.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/Enter_CPR_.c.o
.PHONY : Enter_CPR_.c.o

Enter_CPR_.i: Enter_CPR_.c.i
.PHONY : Enter_CPR_.i

# target to preprocess a source file
Enter_CPR_.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/Enter_CPR_.c.i
.PHONY : Enter_CPR_.c.i

Enter_CPR_.s: Enter_CPR_.c.s
.PHONY : Enter_CPR_.s

# target to generate assembly for a file
Enter_CPR_.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/Enter_CPR_.c.s
.PHONY : Enter_CPR_.c.s

cJSON.o: cJSON.c.o
.PHONY : cJSON.o

# target to build an object file
cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/cJSON.c.o
.PHONY : cJSON.c.o

cJSON.i: cJSON.c.i
.PHONY : cJSON.i

# target to preprocess a source file
cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/cJSON.c.i
.PHONY : cJSON.c.i

cJSON.s: cJSON.c.s
.PHONY : cJSON.s

# target to generate assembly for a file
cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/cJSON.c.s
.PHONY : cJSON.c.s

dosagecalc.o: dosagecalc.c.o
.PHONY : dosagecalc.o

# target to build an object file
dosagecalc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/dosagecalc.c.o
.PHONY : dosagecalc.c.o

dosagecalc.i: dosagecalc.c.i
.PHONY : dosagecalc.i

# target to preprocess a source file
dosagecalc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/dosagecalc.c.i
.PHONY : dosagecalc.c.i

dosagecalc.s: dosagecalc.c.s
.PHONY : dosagecalc.s

# target to generate assembly for a file
dosagecalc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/dosagecalc.c.s
.PHONY : dosagecalc.c.s

login.o: login.c.o
.PHONY : login.o

# target to build an object file
login.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/login.c.o
.PHONY : login.c.o

login.i: login.c.i
.PHONY : login.i

# target to preprocess a source file
login.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/login.c.i
.PHONY : login.c.i

login.s: login.c.s
.PHONY : login.s

# target to generate assembly for a file
login.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/login.c.s
.PHONY : login.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/main.c.s
.PHONY : main.c.s

patient_information.o: patient_information.c.o
.PHONY : patient_information.o

# target to build an object file
patient_information.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/patient_information.c.o
.PHONY : patient_information.c.o

patient_information.i: patient_information.c.i
.PHONY : patient_information.i

# target to preprocess a source file
patient_information.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/patient_information.c.i
.PHONY : patient_information.c.i

patient_information.s: patient_information.c.s
.PHONY : patient_information.s

# target to generate assembly for a file
patient_information.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/medcine.dir/build.make CMakeFiles/medcine.dir/patient_information.c.s
.PHONY : patient_information.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... medcine"
	@echo "... Enter_CPR_.o"
	@echo "... Enter_CPR_.i"
	@echo "... Enter_CPR_.s"
	@echo "... cJSON.o"
	@echo "... cJSON.i"
	@echo "... cJSON.s"
	@echo "... dosagecalc.o"
	@echo "... dosagecalc.i"
	@echo "... dosagecalc.s"
	@echo "... login.o"
	@echo "... login.i"
	@echo "... login.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... patient_information.o"
	@echo "... patient_information.i"
	@echo "... patient_information.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

